#!/usr/bin/env python3
from pathlib import Path
import argparse
import json
import glob

parser = argparse.ArgumentParser(description='A script to create a json file which will be input to Andrews skimming setup for the nanoAOD files generated by CRAB for MC. For data the number of directories are few, create the json by hand')
parser.add_argument('--basePath',help="Enter base path of Location of Root Files typivcally till the directory with year_MC/Data without / at the end",required=True)
parser.add_argument('--out',help="enter the full path end with the file name with .json extention")
parser.add_argument('--search',help="search phrase in dataset name",required=True)
args = parser.parse_args()

keyname_list = []



base_path = Path(args.basePath)
searchPhrase = args.search
listDict = {}
#f = open("fileList.json", "a")
#f.write('{'+'\n')


for dataset in base_path.iterdir():
    if not dataset.is_dir():
        continue
    

    if searchPhrase in dataset.name:
        for name in glob.glob(args.basePath+ '/' + dataset.name+'/*/*'): 
            keyname = f'{dataset.name[:dataset.name.index(searchPhrase)]}'
            print ("keyname = ",keyname, '/n')
            if any(keyname in i for i in keyname_list):
                print ("keyname = ",keyname, keyname_list)
                name2 = args.basePath+ '/' + dataset.name+ '/' + name.split('/')[-3]
                #print ("name 2 = ", name2)
                keyname = keyname + "_" + (name2.split('/')[-1]).split('_')[-2] + "_" + (name2.split('/')[-1]).split('_')[-1]
                keyname_list.append(keyname)
            else:
                keyname_list.append(keyname)
            listDict[keyname]=name+"/*/*.root"


with open(args.out, 'w') as writeFile:
        json.dump(listDict, writeFile, indent=4)

